# Generated by Django 3.0.6 on 2020-05-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200525_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='durationTill',
            new_name='duration_Till',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='durationfrom',
            new_name='duration_from',
        ),
    ]
