# Generated by Django 3.0.6 on 2020-05-27 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200525_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibility',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
